# Generated by Django 5.1.2 on 2024-10-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="day",
            field=models.CharField(default="monday", max_length=9),
        ),
    ]
