# Generated by Django 5.1.2 on 2024-10-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_app", "0002_timeslot_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="camera_ids",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
