# Generated by Django 5.1.2 on 2024-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_app", "0003_timeslot_camera_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot", name="ids", field=models.JSONField(null=True),
        ),
    ]
